import "./globals.css";
import "../style/index.scss";
import AppProvider from "@/contextApi/AppProvider";
import ReduxProvider from "@/redux/provider";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "RAHSM - Rashm Academy of Health & Safety Management",
  description: "Rashm Academy of Health & Safety Management (RAHSM) is a premier safety institute in Gorakhpur, India, offering a wide range of courses in industrial safety, fire safety, and disaster management. Our mission is to empower individuals with the skills and knowledge needed to ensure workplace safety and build a successful career in the safety sector.",
  keywords: "RAHSM, Rashm Academy, Safety Institute, Gorakhpur, Safety Courses, Health and Safety, Safety Training, Job Support, Industrial Safety, Fire Safety, Disaster Management",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <head>
          <meta httpEquiv="x-ua-compatible" content="ie=edge" />
          <meta name="description" content="Generated by create next app" />
          <meta name="robots" content="noindex, follow" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
          />
          <link rel="icon" href="/favicon.png" />
          <link
            href="https://fonts.googleapis.com/css2?family=Hind:wght@300;400;500;600;700&display=swap"
            rel="stylesheet"
          ></link>
        </head>

        <body>
          <ReduxProvider>
            <AppProvider>{children}</AppProvider>
            <ToastContainer />
          </ReduxProvider>
        </body>
      </html>
    </>
  );
}
